"""Pipeline orchestrator: detect -> convert -> validate -> store -> ingest.

Conversion and validation are CPU/IO-bound sync operations. They run in a
thread via asyncio.to_thread() to avoid blocking the event loop (which would
freeze SSE streams and health checks during processing).
"""

import asyncio
import logging
import os
import tempfile
import uuid
from dataclasses import dataclass
from datetime import UTC

import httpx

from src.config import get_settings
from src.models import (
    Dataset,
    DatasetType,
    FormatPair,
    Job,
    JobStatus,
    StageProgress,
    ValidationCheck,
)
from src.services import pmtiles_ingest, stac_ingest, vector_ingest
from src.services.error_mapping import map_pipeline_error
from src.services.detector import detect_format, validate_magic_bytes
from src.services.storage import StorageService

logger = logging.getLogger(__name__)

VALIDATION_CHECK_COUNTS: dict[FormatPair, int] = {
    FormatPair.GEOTIFF_TO_COG: 8,
    FormatPair.NETCDF_TO_COG: 8,
    FormatPair.HDF5_TO_COG: 7,
    FormatPair.GEOJSON_TO_GEOPARQUET: 10,
    FormatPair.SHAPEFILE_TO_GEOPARQUET: 10,
}


def validate_geojson_structure(raw_bytes: bytes) -> None:
    """Validate that raw bytes are a well-formed GeoJSON FeatureCollection.

    Raises ValueError with a descriptive message if validation fails.
    """
    from geojson_pydantic import FeatureCollection
    from pydantic import ValidationError

    try:
        FeatureCollection.model_validate_json(raw_bytes)
    except ValidationError as e:
        raise ValueError(f"Invalid GeoJSON structure: {e}") from e


def get_credits(format_pair: FormatPair, use_pmtiles: bool = False) -> list[dict]:
    """Return the credits list for a given conversion path."""
    credits = []

    if format_pair == FormatPair.GEOTIFF_TO_COG:
        credits.append(
            {
                "tool": "rio-cogeo",
                "url": "https://github.com/cogeotiff/rio-cogeo",
                "role": "Converted by",
            }
        )
    elif format_pair == FormatPair.NETCDF_TO_COG:
        credits.append(
            {"tool": "xarray", "url": "https://xarray.dev", "role": "Read by"}
        )
        credits.append(
            {
                "tool": "rio-cogeo",
                "url": "https://github.com/cogeotiff/rio-cogeo",
                "role": "Converted by",
            }
        )
    elif format_pair == FormatPair.HDF5_TO_COG:
        credits.append(
            {"tool": "h5py", "url": "https://www.h5py.org", "role": "Read by"}
        )
        credits.append(
            {
                "tool": "rasterio",
                "url": "https://rasterio.readthedocs.io",
                "role": "Reprojected by",
            }
        )
        credits.append(
            {
                "tool": "rio-cogeo",
                "url": "https://github.com/cogeotiff/rio-cogeo",
                "role": "Converted by",
            }
        )
    elif format_pair in (
        FormatPair.SHAPEFILE_TO_GEOPARQUET,
        FormatPair.GEOJSON_TO_GEOPARQUET,
    ):
        credits.append(
            {
                "tool": "GeoPandas",
                "url": "https://geopandas.org",
                "role": "Converted by",
            }
        )

    if format_pair.dataset_type == DatasetType.RASTER:
        credits.append(
            {
                "tool": "TiTiler",
                "url": "https://developmentseed.org/titiler",
                "role": "Tiles served by",
            }
        )
        credits.append(
            {
                "tool": "pgSTAC",
                "url": "https://github.com/stac-utils/pgstac",
                "role": "Cataloged by",
            }
        )
    elif use_pmtiles:
        credits.append(
            {
                "tool": "tippecanoe",
                "url": "https://github.com/felt/tippecanoe",
                "role": "Tiles generated by",
            }
        )
        credits.append(
            {
                "tool": "PMTiles",
                "url": "https://github.com/protomaps/PMTiles",
                "role": "Tiles served by",
            }
        )
    else:
        credits.append(
            {
                "tool": "tipg",
                "url": "https://github.com/developmentseed/tipg",
                "role": "Tiles served by",
            }
        )

    credits.append(
        {"tool": "MapLibre", "url": "https://maplibre.org", "role": "Map rendered by"}
    )
    return credits


def _extract_bounds(output_path: str, dataset_type: DatasetType) -> list[float]:
    """Extract [west, south, east, north] bounds in EPSG:4326."""
    if dataset_type == DatasetType.RASTER:
        import rasterio
        from rasterio.warp import transform_bounds

        with rasterio.open(output_path) as src:
            if src.crs and str(src.crs) != "EPSG:4326":
                return list(transform_bounds(src.crs, "EPSG:4326", *src.bounds))
            b = src.bounds
            return [b.left, b.bottom, b.right, b.top]
    else:
        import geopandas as gpd

        gdf = gpd.read_parquet(output_path)
        b = gdf.total_bounds  # [minx, miny, maxx, maxy]
        return [float(b[0]), float(b[1]), float(b[2]), float(b[3])]


@dataclass
class BandMetadata:
    band_count: int
    band_names: list[str]
    color_interpretation: list[str]
    dtype: str


def _extract_band_metadata(output_path: str) -> BandMetadata:
    """Extract band count, names, color interpretation, and dtype from a raster."""
    import rasterio

    with rasterio.open(output_path) as src:
        band_names = [
            desc if desc else f"Band {i + 1}" for i, desc in enumerate(src.descriptions)
        ]
        color_interp = [ci.name for ci in src.colorinterp]
        return BandMetadata(
            band_count=src.count,
            band_names=band_names,
            color_interpretation=color_interp,
            dtype=str(src.dtypes[0]),
        )


def _extract_feature_stats(parquet_path: str) -> tuple[int, list[str]]:
    """Return (feature_count, geometry_types) from a GeoParquet file.

    geometry_types is sorted by frequency, most common first.
    """
    import geopandas as gpd

    gdf = gpd.read_parquet(parquet_path)
    feature_count = len(gdf)
    if feature_count == 0:
        return 0, []
    geometry_types = gdf.geometry.geom_type.value_counts().index.tolist()
    return feature_count, geometry_types


@dataclass
class RasterGeoMetadata:
    crs: str | None
    crs_name: str | None
    pixel_width: int
    pixel_height: int
    resolution: float | None
    compression: str | None


def _extract_raster_geo_metadata(output_path: str) -> RasterGeoMetadata:
    """Extract CRS, dimensions, resolution, and compression from a raster file."""
    import rasterio

    with rasterio.open(output_path) as src:
        return RasterGeoMetadata(
            crs=str(src.crs) if src.crs else None,
            crs_name=src.crs.to_wkt().split('"')[1] if src.crs else None,
            pixel_width=src.width,
            pixel_height=src.height,
            resolution=abs(src.res[0]) if src.res else None,
            compression=src.profile.get("compress", None),
        )


@dataclass
class VectorGeoMetadata:
    crs: str | None
    crs_name: str | None


def _extract_vector_geo_metadata(parquet_path: str) -> VectorGeoMetadata:
    """Extract CRS from a GeoParquet file."""
    import geopandas as gpd

    gdf = gpd.read_parquet(parquet_path)
    crs = gdf.crs
    return VectorGeoMetadata(
        crs=str(crs) if crs else None,
        crs_name=crs.to_wkt().split('"')[1] if crs else None,
    )


def _extract_zoom_range_raster(cog_path: str) -> tuple[int, int]:
    """Derive min/max tile zoom from a COG's native resolution and overview count."""
    import math

    import rasterio
    from rasterio.crs import CRS
    from rasterio.warp import transform_bounds

    with rasterio.open(cog_path) as src:
        if src.crs and not src.crs.is_geographic:
            bounds = transform_bounds(src.crs, CRS.from_epsg(4326), *src.bounds)
        else:
            b = src.bounds
            bounds = (b.left, b.bottom, b.right, b.top)

        width_deg = bounds[2] - bounds[0]
        if width_deg <= 0 or src.width <= 0:
            return 0, 0

        native_pixel_deg = width_deg / src.width
        max_zoom = max(0, min(20, round(math.log2(360.0 / (native_pixel_deg * 256)))))
        n_overviews = len(src.overviews(1))
        min_zoom = max(0, max_zoom - n_overviews)
        return min_zoom, max_zoom


def _detect_use_pmtiles(output_path: str) -> bool:
    """Return True for all vector datasets — PMTiles is the default tile path."""
    return True


async def run_pipeline(job: Job, input_path: str, db_session_factory) -> None:
    """Execute the full conversion pipeline. Updates job status in-place.

    This function is called from a BackgroundTask. It catches all exceptions
    and sets job.status = FAILED with an error message rather than crashing.
    """
    storage = StorageService()

    try:
        # Stage 1: Scan
        job.status = JobStatus.SCANNING
        job.stage_progress = None
        format_pair = detect_format(job.filename)
        job.format_pair = format_pair
        validate_magic_bytes(input_path, format_pair)
        original_file_size = os.path.getsize(input_path)

        # Variable selection for HDF5/NetCDF
        if format_pair in (FormatPair.HDF5_TO_COG, FormatPair.NETCDF_TO_COG):
            from datetime import datetime as dt

            from src.services import scanner
            from src.state import scan_store, scan_store_lock

            if format_pair == FormatPair.HDF5_TO_COG:
                variables = await asyncio.to_thread(scanner.scan_hdf5, input_path)
            else:
                variables = await asyncio.to_thread(scanner.scan_netcdf, input_path)

            if len(variables) == 0:
                job.status = JobStatus.FAILED
                job.error = "No eligible raster variables found in this file."
                return

            if len(variables) > 1:
                scan_id = str(uuid.uuid4())
                job.scan_result = {"scan_id": scan_id, "variables": variables}
                job.scan_event = asyncio.Event()

                async with scan_store_lock:
                    scan_store[scan_id] = {
                        "path": input_path,
                        "job": job,
                        "created_at": dt.now(UTC),
                        "variables": variables,
                        "state": "waiting",
                    }

                await job.scan_event.wait()

                temporal_params = None
                async with scan_store_lock:
                    if scan_id in scan_store:
                        scan_store[scan_id]["state"] = "converting"
                        temporal_params = scan_store[scan_id].get("temporal")

                if temporal_params is not None:
                    from src.services.temporal_pipeline import (
                        run_infile_temporal_pipeline,
                    )

                    await run_infile_temporal_pipeline(
                        job=job,
                        input_path=input_path,
                        variable=job.variable,
                        group=job.group or "",
                        start_index=temporal_params.start_index,
                        end_index=temporal_params.end_index,
                        db_session_factory=db_session_factory,
                    )
                    return

            elif len(variables) == 1:
                v = variables[0]
                job.variable = v["name"]
                job.group = v.get("group", "")

                if v.get("time_dim") and v["time_dim"]["size"] > 1:
                    scan_id = str(uuid.uuid4())
                    job.scan_result = {
                        "scan_id": scan_id,
                        "variables": variables,
                    }
                    job.scan_event = asyncio.Event()

                    async with scan_store_lock:
                        scan_store[scan_id] = {
                            "path": input_path,
                            "job": job,
                            "created_at": dt.now(UTC),
                            "variables": variables,
                            "state": "waiting",
                        }

                    await job.scan_event.wait()

                    temporal_params = None
                    async with scan_store_lock:
                        if scan_id in scan_store:
                            scan_store[scan_id]["state"] = "converting"
                            temporal_params = scan_store[scan_id].get("temporal")

                    if temporal_params is not None:
                        from src.services.temporal_pipeline import (
                            run_infile_temporal_pipeline,
                        )

                        await run_infile_temporal_pipeline(
                            job=job,
                            input_path=input_path,
                            variable=job.variable,
                            group=job.group or "",
                            start_index=temporal_params.start_index,
                            end_index=temporal_params.end_index,
                            db_session_factory=db_session_factory,
                        )
                        return

        # Upload raw file to S3
        storage.upload_raw(input_path, job.dataset_id, job.filename)

        # Stage 2: Convert
        job.status = JobStatus.CONVERTING
        job.stage_progress = None

        if format_pair.dataset_type == DatasetType.RASTER:
            out_filename = os.path.splitext(job.filename)[0] + ".tif"
        else:
            out_filename = os.path.splitext(job.filename)[0] + ".parquet"

        with tempfile.TemporaryDirectory() as tmpdir:
            output_path = os.path.join(tmpdir, out_filename)

            await asyncio.to_thread(
                _import_and_convert,
                format_pair,
                input_path,
                output_path,
                variable=job.variable,
                group=job.group,
            )

            # Stage 3: Validate
            job.status = JobStatus.VALIDATING
            check_count = VALIDATION_CHECK_COUNTS.get(format_pair, 0)
            job.stage_progress = StageProgress(detail=f"{check_count} checks")
            check_results = await asyncio.to_thread(
                _import_and_validate,
                format_pair,
                input_path,
                output_path,
                variable=job.variable,
                group=job.group,
            )
            job.validation_results = [
                ValidationCheck(name=c.name, passed=c.passed, detail=c.detail)
                for c in check_results
            ]

            failed = [c for c in check_results if not c.passed]
            if failed:
                details = "; ".join(f"{c.name}: {c.detail}" for c in failed)
                logger.warning("Validation failed: %s", details)
                job.status = JobStatus.FAILED
                job.error = f"Validation failed: {details}"
                return

            # Validate GeoJSON structure for vector uploads
            if format_pair == FormatPair.GEOJSON_TO_GEOPARQUET:
                from pathlib import Path

                try:
                    validate_geojson_structure(Path(input_path).read_bytes())
                except ValueError as e:
                    job.status = JobStatus.FAILED
                    job.error = str(e)
                    return

            # Extract bounds for auto-zoom
            bounds = await asyncio.to_thread(
                _extract_bounds, output_path, format_pair.dataset_type
            )

            # Extract band metadata for rasters (used by the frontend to determine colormap eligibility)
            band_meta = None
            raster_geo_meta = None
            if format_pair.dataset_type == DatasetType.RASTER:
                band_meta = await asyncio.to_thread(_extract_band_metadata, output_path)
                raster_geo_meta = await asyncio.to_thread(
                    _extract_raster_geo_metadata, output_path
                )

            # Raster converted_file_size: output_path IS the COG at this point
            converted_file_size = (
                os.path.getsize(output_path)
                if format_pair.dataset_type == DatasetType.RASTER
                else None
            )

            # Extract feature stats (vector only)
            feature_count = None
            geometry_types = None
            geoparquet_file_size = None
            vector_geo_meta = None
            if format_pair.dataset_type == DatasetType.VECTOR:
                feature_count, geometry_types = await asyncio.to_thread(
                    _extract_feature_stats, output_path
                )
                vector_geo_meta = await asyncio.to_thread(
                    _extract_vector_geo_metadata, output_path
                )

            # Extract zoom range (vector PMTiles path sets these below via ingest_pmtiles)
            min_zoom = None
            max_zoom = None

            # Compute raster stats for client-side rendering
            raster_min = None
            raster_max = None
            if format_pair.dataset_type == DatasetType.RASTER:
                from src.services.temporal_validation import compute_global_stats

                raster_min, raster_max = await asyncio.to_thread(
                    compute_global_stats, [output_path]
                )

            # Stage 4: Ingest
            job.status = JobStatus.INGESTING
            job.stage_progress = StageProgress(detail="storing")

            converted_key = await asyncio.to_thread(
                storage.upload_converted, output_path, job.dataset_id, out_filename
            )
            job.stage_progress = StageProgress(detail="registering")
            s3_href = storage.get_s3_uri(converted_key)

            use_pmtiles = False
            if format_pair.dataset_type == DatasetType.RASTER:
                tile_url = await stac_ingest.ingest_raster(
                    job.dataset_id,
                    output_path,
                    s3_href,
                    job.filename,
                )
                min_zoom, max_zoom = await asyncio.to_thread(
                    _extract_zoom_range_raster, output_path
                )
            else:
                use_pmtiles = await asyncio.to_thread(_detect_use_pmtiles, output_path)
                geoparquet_file_size = os.path.getsize(output_path)
                if use_pmtiles:
                    (
                        tile_url,
                        min_zoom,
                        max_zoom,
                        converted_file_size,
                    ) = await asyncio.to_thread(
                        pmtiles_ingest.ingest_pmtiles,
                        job.dataset_id,
                        output_path,
                    )
                else:
                    converted_file_size = os.path.getsize(output_path)
                    tile_url = await asyncio.to_thread(
                        vector_ingest.ingest_vector,
                        job.dataset_id,
                        output_path,
                    )
                    await _wait_for_tipg_collection(job.dataset_id)

        # Stage 5: Ready
        job.status = JobStatus.READY
        job.stage_progress = None

        dataset = Dataset(
            id=job.dataset_id,
            filename=job.filename,
            dataset_type=format_pair.dataset_type,
            format_pair=format_pair,
            tile_url=tile_url,
            bounds=bounds,
            band_count=band_meta.band_count if band_meta else None,
            band_names=band_meta.band_names if band_meta else None,
            color_interpretation=band_meta.color_interpretation if band_meta else None,
            dtype=band_meta.dtype if band_meta else None,
            original_file_size=original_file_size,
            converted_file_size=converted_file_size,
            geoparquet_file_size=geoparquet_file_size,
            feature_count=feature_count,
            geometry_types=geometry_types,
            min_zoom=min_zoom,
            max_zoom=max_zoom,
            stac_collection_id=f"sandbox-{job.dataset_id}"
            if format_pair.dataset_type == DatasetType.RASTER
            else None,
            pg_table=vector_ingest.build_table_name(job.dataset_id)
            if (format_pair.dataset_type == DatasetType.VECTOR and not use_pmtiles)
            else None,
            parquet_url=f"/storage/{converted_key}"
            if format_pair.dataset_type == DatasetType.VECTOR
            else None,
            cog_url=f"/storage/{converted_key}"
            if format_pair.dataset_type == DatasetType.RASTER
            else None,
            validation_results=job.validation_results,
            credits=get_credits(format_pair, use_pmtiles=use_pmtiles),
            workspace_id=job.workspace_id,
            created_at=job.created_at,
            raster_min=raster_min,
            raster_max=raster_max,
            crs=raster_geo_meta.crs
            if raster_geo_meta
            else (vector_geo_meta.crs if vector_geo_meta else None),
            crs_name=raster_geo_meta.crs_name
            if raster_geo_meta
            else (vector_geo_meta.crs_name if vector_geo_meta else None),
            pixel_width=raster_geo_meta.pixel_width if raster_geo_meta else None,
            pixel_height=raster_geo_meta.pixel_height if raster_geo_meta else None,
            resolution=raster_geo_meta.resolution if raster_geo_meta else None,
            compression=raster_geo_meta.compression if raster_geo_meta else None,
        )
        from src.models.dataset import persist_dataset

        persist_dataset(db_session_factory, dataset)

    except Exception as e:
        logger.exception("Pipeline failed for job %s", job.id)
        job.status = JobStatus.FAILED
        job.error = map_pipeline_error(e)


async def _wait_for_tipg_collection(dataset_id: str, timeout: float = 30.0) -> None:
    """Poll tipg until it has discovered the new collection, or timeout."""
    settings = get_settings()
    table = vector_ingest.build_table_name(dataset_id)
    collection_id = f"public.{table}"
    url = f"{settings.vector_tiler_url}/collections/{collection_id}"
    deadline = asyncio.get_event_loop().time() + timeout
    async with httpx.AsyncClient() as client:
        while asyncio.get_event_loop().time() < deadline:
            try:
                resp = await client.get(
                    url, headers={"Accept": "application/json"}, timeout=5.0
                )
                if resp.status_code == 200:
                    return
            except Exception:
                pass
            await asyncio.sleep(1.0)


def _import_and_convert(
    format_pair: FormatPair,
    input_path: str,
    output_path: str,
    variable: str | None = None,
    group: str | None = None,
) -> None:
    """Import the appropriate cng-toolkit converter and run it."""
    if format_pair == FormatPair.GEOTIFF_TO_COG:
        from geotiff_to_cog import convert

        convert(input_path, output_path, verbose=True)
    elif format_pair == FormatPair.SHAPEFILE_TO_GEOPARQUET:
        from shapefile_to_geoparquet import convert

        convert(input_path, output_path, verbose=True)
    elif format_pair == FormatPair.GEOJSON_TO_GEOPARQUET:
        from geojson_to_geoparquet import convert

        convert(input_path, output_path, verbose=True)
    elif format_pair == FormatPair.NETCDF_TO_COG:
        from netcdf_to_cog import convert

        kwargs = {"verbose": True}
        if variable:
            kwargs["variable"] = variable
        convert(input_path, output_path, **kwargs)
    elif format_pair == FormatPair.HDF5_TO_COG:
        from hdf5_to_cog import convert

        convert(
            input_path,
            output_path,
            variable=variable or "",
            group=group or "",
            verbose=True,
        )
    else:
        raise ValueError(f"Unknown format pair: {format_pair}")


def _import_and_validate(
    format_pair: FormatPair,
    input_path: str,
    output_path: str,
    variable: str | None = None,
    group: str | None = None,
) -> list:
    """Import the appropriate cng-toolkit validator and run checks."""
    if format_pair == FormatPair.GEOTIFF_TO_COG:
        from geotiff_to_cog import run_checks
    elif format_pair == FormatPair.SHAPEFILE_TO_GEOPARQUET:
        from shapefile_to_geoparquet import run_checks
    elif format_pair == FormatPair.GEOJSON_TO_GEOPARQUET:
        from geojson_to_geoparquet import run_checks
    elif format_pair == FormatPair.NETCDF_TO_COG:
        from netcdf_to_cog import run_checks

        return run_checks(input_path, output_path, variable=variable)
    elif format_pair == FormatPair.HDF5_TO_COG:
        from hdf5_to_cog import run_checks

        return run_checks(
            input_path, output_path, variable=variable or "", group=group or ""
        )
    else:
        raise ValueError(f"Unknown format pair: {format_pair}")
    return run_checks(input_path, output_path)
